# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: MechyMadness
email: zwjong98@gmail.com
description: Understanding Engineering the intuitive way
baseurl: "/MechyMadness" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site
github_username:  baby-wei
whatsapp: 016 878 8392
gmail: zwjong98@gmail.com
paginate: 5
theme-dark: true #Set to true to change to dark website theme

plugins: [jekyll-paginate, kramdown]
# Build settings
markdown: kramdown
